### ISSUE TITLE
Wishlist feature appears to be Chrome-specific

### ISSUE THREAD

**Issue by zipporah8** [carmelyne/secretsanta#5]
I don't use Chrome (didn't even have it installed actually). However, I found that the wishlists don't display when using other browsers. Upon installing Chrome to test it out, there are the wishlists. Even though it is G+, I would imagine I'm not the only user who doesn't use Chrome by default.

**Comment by carmelyne** [comment]
It's been tested on Firefox and Safari as well. You may have Firefox addons that's not allowing you to view the lists.
